### ISSUE TITLE
프로필 introduction 수정 오류

### ISSUE THREAD

**Issue by wjdgus000000000** [CSID-DGU/2023-1-OSSP2-WeAreBility-3#116]
프로필 수정 중 introduction 수정 후 put 할 때 상태코드 500 반환됩니다

**Comment by wjdgus000000000** [comment]
수정 내용을 텍스트 입력창에 받아 newIntro로 저장한 후
final response = await profileApiService.putRequest('user', {
      'introduction': newIntro,
    }) 형태로 사용하였습니다

**Comment by wjdgus000000000** [comment]
Future<http.Response> putRequest(String endpoint, dynamic body) async {
    try {
      final tokens = await getTokens();
      final accessToken = tokens['accessToken'];
      final refreshToken = tokens['refreshToken'];

      final response = await http.put(
        Uri.parse('$baseUrl/$endpoint'),
        headers: {
          'Authorization': 'Bearer $accessToken',
          'Content-Type': 'application/json',
        },
        body: jsonEncode(body),
      );

      if (response.statusCode == 200) {
        print('PUT 요청 성공');
      } else {
        print('PUT 요청 실패 - 상태 코드: ${response.statusCode}');
      }

      return response;
    } catch (e) {
      print('PUT 요청 실패 - $e');
      return http.Response('Error', 0);
    }
  }

**Comment by HyungJoonSon** [comment]
name은 따로 넣으셨나요??

**Comment by wjdgus000000000** [comment]
name은 같은 방식으로 따로 수정하도록 했는데 수정하고 저장까지 잘 됩니당 ..

**Comment by HyungJoonSon** [comment]
아마 name은 not null 옵션이 있어 값이 필요한 거 같고, 소개글의 경우는 not null  옵션이 없어서 둘의 차이가 있는 거 같습니다.

**Comment by HyungJoonSon** [comment]
프로필 수정할 때, name 또는 소개글 값이 변경되지 않더라도, 그 전 값을 같이 넣어서 보내주시면 될 거 같아요.
