### ISSUE TITLE
등록 및 완주 확인 시 사용되는 check 사용시 무조건 True가 나오는 경우가 있습니다.

### ISSUE THREAD

**Issue by HyungJoonSon** [CSID-DGU/2023-1-OSSP2-WeAreBility-3#77]
Check  AI Function 사용시 계속  True가 나오는 Error 가 있는 거 같습니다.

확인 부탁드려요!

2번 산책로에 [3, 4, 5] 번 등의 산책로를 넣어도 True Value가 나옵니다.

**Comment by Hoin666** [comment]
체크해봤는데 checker는 문제없고 finisher에서 문제가 발생하는 것 같습니다.

checker와 finisher의 로직이 같은데, 둘의 threshold가 달라서 발생하는 문제인것 같습니다.

이게 굉장히 애매한게 checker로 등록을 심사할 때는 깐깐하게 보는게 맞는거 같아서 threshold가 0.9985이고 유사도가 0.9985보다 크면  등록 안되게 끔 되어 있는데, finisher는 완주여부를 판단하는 거니까 threshold를 0.8로 확 낮추어서 이것보다만 높으면 완주했다고 판단했습니다. 하지만 2번 산책로에 3, 4 5,번을 찍어본 결과 유사도 점수가 0.89 ~ 0.91 대에서 노는 걸 확인했는데 이정도면 finisher의 threshold를 0.95 정도로 설정하면 문제 없을 것 같습니당

**Comment by HyungJoonSon** [comment]
DB Select result가 달라서 생긴 오류였습니다!
